import { StyleSheet } from 'react-native';
import { INITIAL_LAYOUT, MIN_TOUCH_TARGET } from './stopwatchForm.shared';

const IS_TABLET = INITIAL_LAYOUT.isTablet;
const IS_SMALL_PHONE = INITIAL_LAYOUT.isSmallPhone;
const USE_TWO_COLUMN_PENALTIES = INITIAL_LAYOUT.penaltyColumns > 1;
const CARD_WIDTH = INITIAL_LAYOUT.categoryCardWidth;

const styles = StyleSheet.create({
  card: {
    width: CARD_WIDTH,
    backgroundColor: '#111722',
    borderWidth: 1,
    borderColor: '#cfdcf0',
    minHeight: IS_TABLET ? 320 : 276,
    borderRadius: 22,
    paddingHorizontal: IS_TABLET ? 12 : 10,
    paddingVertical: IS_TABLET ? 12 : 10,
    elevation: 5,
    shadowColor: '#1f3b73',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  cardContent: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'space-between',
  },
  iconBox: {
    width: '100%',
    flex: 1,
    minHeight: IS_TABLET ? 188 : 156,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    overflow: 'hidden',
  },
  categoryIcon: {
    fontSize: IS_TABLET ? 34 : 30,
  },
  categoryImageIcon: {
    width: IS_TABLET ? '130%' : '120%',
    height: IS_TABLET ? '112%' : '108%',
    alignSelf: 'center',
  },
  categoryImageIconSuvModified: {
    width: IS_TABLET ? '106%' : '100%',
    height: IS_TABLET ? '98%' : '94%',
  },
  categoryImageIconPetrolModified: {
    width: IS_TABLET ? '110%' : '103%',
    height: IS_TABLET ? '98%' : '95%',
  },
  categoryImageIconPetrolExpert: {
    width: IS_TABLET ? '170%' : '160%',
    height: IS_TABLET ? '142%' : '136%',
  },
  countPanel: {
    width: '100%',
    marginTop: 'auto',
    marginBottom: 0,
    backgroundColor: '#f8fafc',
    borderTopWidth: 1,
    borderTopColor: '#e4e8f0',
    paddingHorizontal: IS_TABLET ? 6 : 5,
    paddingTop: IS_TABLET ? 6 : 5,
    paddingBottom: IS_TABLET ? 4 : 3,
    minHeight: IS_TABLET ? 50 : 46,
  },
  countStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  countStat: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: IS_TABLET ? 36 : 34,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: IS_TABLET ? 5 : 4,
    paddingVertical: IS_TABLET ? 4 : 3,
  },
  countStatSecondary: {
    borderWidth: 1,
  },
  countStatsDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: '#d7dce6',
    marginHorizontal: IS_TABLET ? 6 : 5,
  },
  countStatValue: {
    fontSize: IS_TABLET ? 14 : 13,
    fontWeight: '800',
    color: '#172238',
    lineHeight: IS_TABLET ? 16 : 15,
  },
  countStatValueOnPrimary: {
    color: '#fff8f1',
  },
  countStatLabel: {
    fontSize: IS_TABLET ? 8 : 7,
    color: '#707b8f',
    fontWeight: '700',
    marginTop: 1,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  countStatLabelOnPrimary: {
    color: '#fff8f1',
  },
  formGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: '#495057',
    marginBottom: 8,
  },
  dropdownButton: {
    borderWidth: 1,
    borderColor: '#dee2e6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: MIN_TOUCH_TARGET,
    backgroundColor: '#111722',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownButtonText: {
    fontSize: 14,
    color: '#fff6ea',
    fontWeight: '500',
  },
  dropdownArrow: {
    fontSize: 12,
    color: '#6c757d',
  },
  dropdownMenu: {
    borderWidth: 1,
    borderColor: '#dee2e6',
    borderTopWidth: 0,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    backgroundColor: '#111722',
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 48,
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  dropdownItemText: {
    fontSize: 14,
    color: '#495057',
  },
  dropdownItemSelected: {
    color: '#007bff',
    fontWeight: '600',
  },
  lateStartCheckboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: MIN_TOUCH_TARGET,
  },
  lateStartCheckboxRowDisabled: {
    opacity: 0.55,
  },
  lateStartCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#f5c542',
    backgroundColor: '#111722',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  lateStartCheckboxChecked: {
    backgroundColor: '#f5c542',
    borderColor: '#d09a00',
  },
  lateStartCheckboxTick: {
    fontSize: 13,
    fontWeight: '800',
    color: '#fff6ea',
  },
  lateStartCheckboxLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#8a5a00',
  },
  lateStartSelectorContainer: {
    width: '100%',
  },
  lateStartSelectorDisabled: {
    opacity: 0.55,
  },
  lateStartSelectorButton: {
    minHeight: MIN_TOUCH_TARGET,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#f5c542',
    backgroundColor: '#fff8e1',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  lateStartSelectorButtonActive: {
    backgroundColor: '#f5c542',
    borderColor: '#d09a00',
  },
  lateStartSelectorButtonText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: '#8a5a00',
  },
  lateStartSelectorButtonTextActive: {
    color: '#fff6ea',
  },
  lateStartSelectorArrow: {
    fontSize: 13,
    color: '#8a5a00',
    marginLeft: 10,
  },
  lateStartSelectorMenu: {
    marginTop: 8,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#f5d77d',
    backgroundColor: '#111722',
  },
  lateStartSelectorItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 48,
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#f6e7b4',
  },
  lateStartSelectorItemText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  lateStartSelectorItemTextSelected: {
    color: '#b7791f',
  },
  lateStartSelectorClearItem: {
    borderBottomWidth: 0,
    backgroundColor: '#fffaf0',
  },
  lateStartSelectorClearText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#8a5a00',
  },
  penaltyCard: {
    width: USE_TWO_COLUMN_PENALTIES ? '48.5%' : '100%',
    backgroundColor: '#fbfcff',
    borderWidth: 1,
    borderColor: '#dce6f4',
    borderRadius: 16,
    paddingHorizontal: IS_TABLET ? 12 : IS_SMALL_PHONE ? 8 : 10,
    paddingVertical: IS_TABLET ? 10 : IS_SMALL_PHONE ? 7 : 8,
    minHeight: IS_TABLET ? 88 : IS_SMALL_PHONE ? 74 : 82,
  },
  penaltyCardLabel: {
    fontSize: IS_TABLET ? 14 : IS_SMALL_PHONE ? 11 : 12,
    fontWeight: '700',
    color: '#4c5c77',
    marginBottom: IS_SMALL_PHONE ? 6 : 8,
  },
  penaltyCardControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  penaltyValueRow: {
    width: '100%',
    alignItems: 'center',
  },
  counterButton: {
    width: IS_TABLET ? 54 : MIN_TOUCH_TARGET,
    height: IS_TABLET ? 54 : MIN_TOUCH_TARGET,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#3565df',
  },
  counterButtonDisabled: {
    backgroundColor: '#cbd5e1',
  },
  counterButtonText: {
    fontSize: IS_TABLET ? 20 : IS_SMALL_PHONE ? 16 : 18,
    fontWeight: '700',
    color: '#fff6ea',
  },
  counterInput: {
    width: IS_TABLET ? 60 : 54,
    height: IS_TABLET ? 54 : MIN_TOUCH_TARGET,
    textAlign: 'center',
    fontSize: IS_TABLET ? 22 : IS_SMALL_PHONE ? 15 : 16,
    fontWeight: '700',
    color: '#111827',
    marginHorizontal: 4,
    backgroundColor: 'transparent',
  },
  penaltyValuePill: {
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: IS_TABLET ? 56 : IS_SMALL_PHONE ? 40 : 44,
    paddingHorizontal: IS_SMALL_PHONE ? 6 : 8,
    paddingVertical: 4,
    backgroundColor: '#dfeafd',
    borderRadius: 8,
  },
  penaltyValue: {
    fontSize: IS_SMALL_PHONE ? 11 : 12,
    fontWeight: '700',
    color: '#3565df',
  },
  dnfCard: {
    width: '100%',
    backgroundColor: '#fff7f3',
    borderWidth: 1,
    borderColor: '#ffd5c7',
    borderRadius: 16,
  },
  dnfCardDisabled: {
    opacity: 0.65,
  },
  dnfToggleButton: {
    minHeight: 52,
    borderRadius: 12,
    backgroundColor: '#111722',
    borderWidth: 1,
    borderColor: '#ffb599',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dnfToggleButtonActive: {
    backgroundColor: '#ff5a1f',
    borderColor: '#ff5a1f',
  },
  dnfToggleButtonDisabled: {
    backgroundColor: '#f3f4f6',
    borderColor: '#d1d5db',
  },
  dnfToggleButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#b23b13',
  },
  dnfToggleButtonTextActive: {
    color: '#fff6ea',
  },
  dnfToggleButtonArrow: {
    fontSize: 13,
    color: '#b23b13',
    marginLeft: 12,
  },
  dnfDropdownMenu: {
    marginTop: 10,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#ffd5c7',
    backgroundColor: '#111722',
  },
  dnfCheckboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 48,
    borderBottomWidth: 1,
    borderBottomColor: '#ffe4da',
  },
  dnfCheckboxRowDisabled: {
    opacity: 0.72,
  },
  dnfRadio: {
    width: 22,
    height: 22,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: '#ffb599',
    backgroundColor: '#111722',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  dnfRadioSelected: {
    borderColor: '#ff5a1f',
  },
  dnfRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#ff5a1f',
  },
  dnfCheckboxContent: {
    flex: 1,
  },
  dnfCheckboxLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  dnfCheckboxLabelDisabled: {
    color: '#6b7280',
  },
  dnfCheckboxHint: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '600',
    color: '#9a3412',
    fontFamily: 'monospace',
  },
  dnfPointsSection: {
    paddingTop: 4,
  },
  dnfPointsLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#9a3412',
    textTransform: 'uppercase',
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 6,
  },
  dnfDropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 48,
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#ffe4da',
  },
  dnfDropdownItemDisabled: {
    backgroundColor: '#f9fafb',
  },
  dnfDropdownItemText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  dnfDropdownItemTextSelected: {
    color: '#ff5a1f',
  },
  dnfDropdownItemTextDisabled: {
    color: '#9ca3af',
  },
  dnfClearButton: {
    borderBottomWidth: 0,
    backgroundColor: '#fff7f3',
  },
  dnfClearButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#b23b13',
  },
});

export default styles;
